import telebot

Main_Reply = telebot.types.ReplyKeyboardMarkup(True)
Button1_k1 = telebot.types.KeyboardButton("АМПЛУА В ВОЛЛЕЙБОЛЕ")
Button2_k1 = telebot.types.KeyboardButton("СХЕМЫ ИГРЫ В ВОЛЛЕЙБОЛ")
Button3_k1 = telebot.types.KeyboardButton("ПОЛЕЗНАЯ ИНФОРМАЦИЯ")
Button4_k1 = telebot.types.KeyboardButton("ВИДЕО - ИГРА В ВОЛЛЕЙБОЛ")
Main_Reply.row(Button1_k1)
Main_Reply.row(Button2_k1)
Main_Reply.row(Button3_k1)
Main_Reply.row(Button4_k1)

Amplua_inline = telebot.types.InlineKeyboardMarkup()
Button_Amplua_All = telebot.types.InlineKeyboardButton("АМПЛУА - ОБЩЕЕ", url="https://youtu.be/9YZj9p_tmJo")
Button_Amplua_Libero = telebot.types.InlineKeyboardButton("АМПЛУА - ЛИБЕРО", url="https://www.youtube.com/watch?v=1PXV1Py2Ceg")
Button_Amplua_Diagonal = telebot.types.InlineKeyboardButton("АМПЛУА - ДИАГОНАЛЬНЫЙ", url="https://www.youtube.com/watch?v=yk-oHGpVweA")
Button_Amplua_Ender = telebot.types.InlineKeyboardButton("АМПЛУА - ДОИГРОВЩИК", url="https://www.youtube.com/watch?v=yk-oHGpVweA")
Button_Amplua_CentralDefender = telebot.types.InlineKeyboardButton("АМПЛУА - ЦЕНТРАЛЬНЫЙ БЛОКИРУЮЩИЙ", url="https://www.youtube.com/watch?v=7NNVFpH-OsM")
Button_Amplua_Svyaz = telebot.types.InlineKeyboardButton("АМПЛУА - СВЯЗУЮЩИЙ", url="https://www.youtube.com/watch?v=ZPnlcjWyj2U")
Amplua_inline.add(Button_Amplua_All)
Amplua_inline.add(Button_Amplua_Libero)
Amplua_inline.add(Button_Amplua_Diagonal)
Amplua_inline.add(Button_Amplua_Ender)
Amplua_inline.add(Button_Amplua_CentralDefender)
Amplua_inline.add(Button_Amplua_Svyaz)

Scheme_Inline = telebot.types.InlineKeyboardMarkup()
Button_Scheme_5_1 = telebot.types.InlineKeyboardButton("СХЕМА 5/1", url="https://www.youtube.com/watch?v=-tGWt8MYjXU&t=180s")
Button_Scheme_5_1_2 = telebot.types.InlineKeyboardButton("СХЕМА 5/1 ВИДЕО 2", url="https://www.youtube.com/watch?v=O0MgsrYFLNM")
Button_Scheme_Positions = telebot.types.InlineKeyboardButton("ПРАВИЛА РАССТАНОВКИ", url="https://www.youtube.com/watch?v=qAS_vnJktC4")
Scheme_Inline.add(Button_Scheme_5_1)
Scheme_Inline.add(Button_Scheme_5_1_2)
Scheme_Inline.add(Button_Scheme_Positions)

Information_Inline = telebot.types.InlineKeyboardMarkup()
Button_Rules = telebot.types.InlineKeyboardButton("ПРАВИЛА ИГРЫ", url="https://www.youtube.com/watch?v=ObZZE8mG3EA")
Button_Gameplay = telebot.types.InlineKeyboardButton("ПРАВИЛЬНАЯ ИГРА", url="https://www.youtube.com/watch?v=L7DgD2s07wo")
Information_Inline.add(Button_Rules)
Information_Inline.add(Button_Gameplay)

Video_Inline = telebot.types.InlineKeyboardMarkup()
Button_Video1 = telebot.types.InlineKeyboardButton("Любительский Воллейбол | Первое Лицо", url="https://www.youtube.com/watch?v=KCxyhzyxP08")
Button_Video2 = telebot.types.InlineKeyboardButton("Чемпионат 'Bright Fit'", url="https://www.youtube.com/watch?v=zM9r_ssl5eA")
Video_Inline.add(Button_Video1)
Video_Inline.add(Button_Video2)